site_name: Users Guide
repo_url: https://github.com/opencast/opencast
edit_uri: edit/develop/docs/guides/user/docs/

# Default theme used is windmill
theme: windmill

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# The css files in this list will override existing css from the default theme
extra_css:
  - css/extra.css

# The javascript files in this list will extend the existing javascript from the default theme
extra_javascript:
  - javascript/extra.js

# The logo in the header
extra:
  logo: 'opencast-white.svg'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order
nav:
- Introduction: 'index.md'
- Log-in: 'login.md'
- Events: 'events.md'
- Series: 'series.md'
- Systems: 'systems.md'
- Users: 'users.md'
- Groups: 'groups.md'
- Access Policies: 'accesspolicies.md'
- Themes: 'themes.md'
- Processing: 'processing.md'
- Video Editor: 'videoeditor.md'
- Asset Manager: 'asset-manager.md'
- Search & Filter: 'searchandfilter.md'
- Configure the UI: 'configure.md'
- Glossary: 'glossary.md'
- Internationalization: 'i18n.md'
- Advanced:
  - Overview: 'advanced/index.md'
  - Capture Agent Access Control: 'advanced/capture-agent-access.md'
  - Role-Based Visibility: 'advanced/role-based-visibility.md'
  - Offloading Event to AWS S3: 'advanced/offload-s3.md'
  - Restoring Events from AWS to local storage: 'advanced/restore.md'
