---

- name: stop opencast
  service:
    name: opencast
    state: stopped
  ignore_errors: true

- name: remove previous deployment
  file:
    path: /opt/opencast-dist-allinone
    state: absent

- name: extract distribution
  unarchive:
    src: 'https://radosgw.public.os.wwu.de/opencast-daily/opencast-dist-allinone-15-SNAPSHOT.tar.gz'
    dest: /opt
    remote_src: true
    owner: root
    group: root

- name: link installation from /opt/opencast
  file:
    src: /opt/opencast-dist-allinone
    dest: /opt/opencast
    owner: root
    group: root
    state: link

# by making the directory writable, we allow Karaf to generate a jetty.xml dynamically
- name: fix for missing configuration
  file:
    path: /opt/opencast/etc
    owner: opencast
    group: opencast

- name: create karaf instances directory
  file:
    path: /opt/opencast-dist-allinone/instances
    state: directory
    mode: '0755'
    owner: opencast
    group: opencast

- name: link to systemd unit
  file:
    src: /opt/opencast/docs/scripts/service/opencast.service
    dest: /etc/systemd/system/opencast.service
    owner: root
    group: root
    state: link

- name: set ownership of storage directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: opencast
    group: opencast
  loop:
    - '{{ opencast_data_path }}'
    - '{{ opencast_fast_data_path }}'

- name: install dependencies
  package:
    name:
      - ffmpeg
      - tesseract
      - tesseract-langpack-deu
      - hunspell
      - nmap-ncat
    state: present

- name: enable JWT stuff
  lineinfile:
    state: present
    path: /opt/opencast/etc/org.apache.karaf.features.cfg
    insertafter: '    opencast-allinone/15.0.0.SNAPSHOT, \\'
    line: '    opencast-security-jwt/15.0.0.SNAPSHOT, \'

- name: configure opencast
  template:
    src: '{{ item }}'
    dest: /opt/opencast/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - etc/custom.properties
    - etc/org.opencastproject.adminui.endpoint.SeriesEndpoint.cfg
    - etc/org.opencastproject.fsresources.StaticResourceServlet.cfg
    - etc/org.opencastproject.liveschedule.impl.LiveScheduleServiceImpl.cfg
    - etc/security/mh_default_org.xml
    - etc/workflows/fast.yaml
    - etc/workflows/schedule-and-upload.xml
    - bin/setenv

- name: User Interface Configuration
  copy:
    dest: /opt/opencast/etc/ui-config/mh_default_org/{{ item }}
    src: '{{ item }}'
  loop:
    - studio/settings.toml
    - editor/editor-settings.toml

# - name: start and enable opencast service
#   systemd:
#     name: opencast.service
#     state: restarted
#     enabled: true
#     daemon_reload: true
