# Ungrouped values, used to make GET-Parameters easier to write
# Values are assigned here only for debugging purposes
#mediaPackageId = '27cd7156-fda6-4b31-aab5-d56833012caf'

# Debugging values
# Should be deleted in production
[debugging]
#ocUrl = 'https://pyca.opencast.org'

[metadata]
show = false

[thumbnail]
show = false