site_name: Opencast - Administration Guide
repo_url: https://bitbucket.org/opencast-community/matterhorn/src/develop/docs/guides/admin/docs

# Default theme used is readthedocs
theme: readthedocs

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order

pages:
- Home: 'index.md'
- Release Notes: 'releasenotes.md'
- Upgrade: 'upgrade.md'
- Changelog: 'changelog.md'
- Installation:
   - Overview: 'installation/index.md'
   - Multiple Servers: 'installation/multiple-servers.md'
   - Installation from Source:
      - Linux: 'installation/source-linux.md'
      - MacOS X: 'installation/source-macosx.md'
   - Installation from Package (RPM):
      - Fedora: 'installation/rpm-fedora.md'
      - RHEL/CentOS: 'installation/rpm-rhel-sl-centos.md'
   - Installation with Docker:
      - Testing Locally: 'installation/docker-local.md'
- Configuration:
   - Overview: 'configuration/index.md'
   - Basic: 'configuration/basic.md'
   - Database: 'configuration/database.md'
   - Asset Manager: 'configuration/asset-manager.md'
   - Message Broker: 'configuration/message-broker.md'
   - Metadata: 'configuration/metadata.md'
   - Encoding: 'configuration/encoding.md'
   - Load: 'configuration/load.md'
   - Logging and Privacy: 'configuration/logging.and.privacy.md'
   - Multi Tenancy: 'configuration/multi.tenancy.md'
   - Security:
      - General Security: 'configuration/security.md'
      - Access Control Lists: 'configuration/acl.md'
      - Authentication and Authorization Infrastructure (AAI): 'configuration/security.aai.md'
      - Central Authentication Service (CAS): 'configuration/security.cas.md'
      - LDAP Authentication and Authorization (without CAS): 'configuration/security.ldap.md'
      - Sakai User Provider: 'configuration/security.user.sakai.md'
      - Stream Security: 'configuration/stream-security.md'
   - Workflow: 'configuration/workflow.md'
   - External API: 'configuration/external-api.md'
   - OAI-PMH: 'configuration/oaipmh.md'
- Modules:
   - Overview: 'modules/index.md'
   - Atom/RSS Feed: 'modules/atomrss.md'
   - AWS S3 Distribution: 'modules/awss3distribution.md'
   - LTI Module: 'modules/ltimodule.md'
   - Media Module: 'modules/mediamodule.configuration.md'
   - Player:
      - Configuration: 'modules/player.configuration.md'
      - URL Parameters: 'modules/player.url.parameter.md'
      - Piwik Tracking: 'modules/player.piwik.tracking.md'
   - Search Index: 'modules/searchindex.md'
   - Stream Security: 'modules/stream-security.md'
   - Text Extraction: 'modules/textextraction.md'
   - Transcripts (IBM Watson): 'modules/watsontranscripts.md'   
   - Video Editor:
      - Setup: 'modules/videoeditor.setup.md'
      - Architecture: 'modules/videoeditor.architecture.md'
   - Video Segmentation: 'modules/videosegmentation.md'
   - Waveform Service: 'modules/waveform.md'
   - YouTube Publication: 'modules/youtubepublication.md'
- Workflow Operation Handler:
   - Overview: 'workflowoperationhandlers/index.md'
   - Analyze Tracks: 'workflowoperationhandlers/analyze-tracks-woh.md'
   - Analyze Audio: 'workflowoperationhandlers/analyzeaudio-woh.md'
   - Asset Snapshot: 'workflowoperationhandlers/asset-snapshot-woh.md'
   - Asset Delete: 'workflowoperationhandlers/asset-delete-woh.md'
   - Attach Watson Transcription: 'workflowoperationhandlers/attach-watson-transcription-woh.md'
   - Cleanup: 'workflowoperationhandlers/cleanup-woh.md'
   - Comment: 'workflowoperationhandlers/comment-woh.md'
   - Compose: 'workflowoperationhandlers/compose-woh.md'
   - Composite: 'workflowoperationhandlers/composite-woh.md'
   - Concat: 'workflowoperationhandlers/concat-woh.md'
   - Configure-By-DCTerm: 'workflowoperationhandlers/configure-by-dcterm-woh.md'
   - Copy: 'workflowoperationhandlers/copy-woh.md'
   - Cover Image: 'workflowoperationhandlers/coverimage-woh.md'
   - Defaults: 'workflowoperationhandlers/defaults-woh.md'
   - Editor: 'workflowoperationhandlers/editor-woh.md'
   - Email: 'workflowoperationhandlers/email-woh.md'
   - Encode: 'workflowoperationhandlers/encode-woh.md'
   - Export Workflow Properties: 'workflowoperationhandlers/export-wf-properties-woh.md'
   - Extract Text: 'workflowoperationhandlers/extracttext-woh.md'
   - HTTP Notify: 'workflowoperationhandlers/httpnotify-woh.md'
   - Image: 'workflowoperationhandlers/image-woh.md'
   - Image to Video: 'workflowoperationhandlers/imagetovideo-woh.md'
   - Import Workflow Properties: 'workflowoperationhandlers/import-wf-properties-woh.md'
   - Incident: 'workflowoperationhandlers/incident-woh.md'
   - Ingest-Download: 'workflowoperationhandlers/ingestdownload-woh.md'
   - Inspect: 'workflowoperationhandlers/inspect-woh.md'
   - Normalize Audio: 'workflowoperationhandlers/normalizeaudio-woh.md'
   - Partial Import: 'workflowoperationhandlers/partial-import-woh.md'
   - Post Media Package: 'workflowoperationhandlers/postmediapackage-woh.md'
   - Prepare A/V: 'workflowoperationhandlers/prepareav-woh.md'
   - Probe Resolution: 'workflowoperationhandlers/probe-resolution-woh.md'
   - Publish AWS: 'workflowoperationhandlers/publishaws-woh.md'
   - Publish Configure: 'workflowoperationhandlers/publishconfigure-woh.md'
   - Publish Engage: 'workflowoperationhandlers/publishengage-woh.md'
   - Publish OAI-PMH: 'workflowoperationhandlers/publish-oaipmh-woh.md'
   - Republish OAI-PMH: 'workflowoperationhandlers/republish-oaipmh-woh.md'
   - Retract AWS S3 and Cloudfront: 'workflowoperationhandlers/retract-aws-woh.md'
   - Retract Engage: 'workflowoperationhandlers/retract-engage-woh.md'
   - Retract Configure: 'workflowoperationhandlers/retractconfigure-woh.md'
   - Retract OAI-PMH: 'workflowoperationhandlers/retract-oaipmh-woh.md'
   - Segment Previews: 'workflowoperationhandlers/segmentpreviews-woh.md'
   - Segment Video: 'workflowoperationhandlers/segmentvideo-woh.md'
   - Series: 'workflowoperationhandlers/series-woh.md'
   - Silence: 'workflowoperationhandlers/silence-woh.md'
   - Start Watson Transcription: 'workflowoperationhandlers/start-watson-transcription-woh.md'
   - Tag: 'workflowoperationhandlers/tag-woh.md'
   - Tag-By-DCTerm: 'workflowoperationhandlers/tag-by-dcterm-woh.md'
   - Theme: 'workflowoperationhandlers/theme-woh.md'
   - Waveform: 'workflowoperationhandlers/waveform-woh.md'
   - Zip: 'workflowoperationhandlers/zip-woh.md'
