site_name: Administration Guide
repo_url: https://github.com/opencast/opencast
edit_uri: edit/develop/docs/guides/admin/docs/

plugins:
  - search:
  - macros:
  - mermaid2:
      arguments:
        theme: neutral

# Default theme used is windmill
theme: windmill

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# The css files in this list will override existing css from the default theme
extra_css:
   - css/extra.css

# The javascript files in this list will extend the existing javascript from the default theme
extra_javascript:
   - javascript/extra.js
   - javascript/popper.js
   - javascript/tippy.js

# The logo in the header
extra:
   logo: 'opencast-white.svg'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order
nav:
- Home: 'index.md'
- Release Notes: 'releasenotes.md'
- Upgrade: 'upgrade.md'
- Changelog: 'changelog.md'
- Registration: 'registration.md'
- Installation:
   - Overview: 'installation/index.md'
   - Hardware Requirements: installation/server-requirements.md
   - Java Versions: installation/java-version.md
   - Multiple Servers: 'installation/multiple-servers.md'
   - Installation from Source:
      - Linux: 'installation/source-linux.md'
      - MacOS X: 'installation/source-macosx.md'
   - Installation from Package:
      - Debian/Ubuntu: 'installation/debs.md'
      - RHEL/CentOS Stream 8/9: 'installation/rpm-el.md'
   - Installation via script:
      - Ansible: 'installation/ansible.md'
   - Installation with Docker:
      - Testing Locally: 'installation/docker-local.md'
   - Prerelease Testing: 'installation/prereleases.md'
- Configuration:
   - Overview: 'configuration/index.md'
   - Basic: 'configuration/basic.md'
   - Database: 'configuration/database.md'
   - HTTPS:
      - Overview: 'configuration/https/index.md'
      - Using Nginx: 'configuration/https/nginx.md'
      - Using Apache httpd: configuration/https/apache-httpd.md
      - Internal HTTPS: 'configuration/https/opencast.only.md'
      - Self-Signed Certificates: 'configuration/https/self-signed-certificates.md'
   - Domain change/HTTPS migration: 'configuration/migration-domain-https.md'
   - Admin UI Configuration:
        - Capture-Agent Access: configuration/admin-ui/capture-agent-access.md
        - Event Filters: 'configuration/admin-ui/event-filters.md'
        - Languages: 'configuration/admin-ui/languages.md'
        - Manual Asset Upload: 'configuration/admin-ui/asset-upload.md'
        - Role-based Visibility: 'configuration/admin-ui/role-based-visibility.md'
        - Statistics: 'configuration/admin-ui/statistics.md'
        - Thumbnails: 'configuration/admin-ui/thumbnails.md'
        - Imprint and Privacy Statement: 'configuration/admin-ui/about.md'
        - Terms of Use: 'configuration/admin-ui/terms.md'
   - Amazon Services:
        - Amazon S3 Archive Storage: 'configuration/awss3archive.md'
        - Amazon S3 Distribution: 'configuration/awss3distribution.md'
   - Asset Manager: 'configuration/asset-manager.md'
   - Authentication, Authorization and User Management:
        - General Security: 'configuration/security.md'
        - Access Control Lists: 'configuration/acl.md'
        - Authentication and Authorization Infrastructure (AAI): 'configuration/security.aai.md'
        - Central Authentication Service (CAS): 'configuration/security.cas.md'
        - LDAP Authentication and Authorization (without CAS): 'configuration/security.ldap.md'
        - JWT-based Authentication and Authorization (e.g. for OIDC): 'configuration/security.jwt.md'
        - Moodle User Provider: 'configuration/security.user.moodle.md'
        - Sakai User Provider: 'configuration/security.user.sakai.md'
        - Brightspace User Provider: 'configuration/security.user.brightspace.md'
        - Canvas User Provider: 'configuration/security.user.canvas.md'
   - Encoding: 'configuration/encoding.md'
   - Execute Service: 'configuration/execute.md'
   - External API: 'configuration/external-api.md'
   - External Monitoring: 'configuration/monitoring.md'
   - Firewall: 'configuration/firewall.md'
   - Inbox: 'configuration/inbox.md'
   - LTI Module: 'configuration/ltimodule.md'
   - List Providers: 'configuration/listproviders.md'
   - Live Schedule: 'configuration/liveschedule.md'
   - Load: 'configuration/load.md'
   - Logging: 'configuration/log.md'
   - Media Module: 'configuration/mediamodule.configuration.md'
   - Metadata: 'configuration/metadata.md'
   - Metrics (OpenMetrics, Prometheus): configuration/metrics.md
   - Multi Tenancy: 'configuration/multi.tenancy.md'
   - OAI-PMH: 'configuration/oaipmh.md'
   - Player:
        - Overview: 'configuration/player/player.overview.md'
        - Paella player 7:
             - Configuration: 'configuration/player/paella.player7/configuration.md'
             - URL Parameters: 'configuration/player/paella.player7/url.parameter.md'
             - Paella plugins:
                 - Overview: 'configuration/player/paella.player7/plugins.md'
                 - org.opencast.paella.cookieconsent: 'configuration/player/paella.player7/plugins/org.opencast.paella.cookieconsent.md'
                 - org.opencast.paella.descriptionPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.descriptionPlugin.md'
                 - org.opencast.paella.downloadsPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.downloadsPlugin.md'
                 - org.opencast.paella.editorPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.editorPlugin.md'
                 - org.opencast.paella.episodesFromSeries: 'configuration/player/paella.player7/plugins/org.opencast.paella.episodesFromSeries.md'
                 - org.opencast.paella.loginPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.loginPlugin.md'
                 - org.opencast.paella.opencast.userTrackingDataPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.opencast.userTrackingDataPlugin.md'
                 - org.opencast.paella.matomo.userTrackingDataPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.matomo.userTrackingDataPlugin.md'
                 - org.opencast.paella.transcriptionsPlugin: 'configuration/player/paella.player7/plugins/org.opencast.paella.transcriptionsPlugin.md'
                 - org.opencast.paella.versionButton.js: 'configuration/player/paella.player7/plugins/org.opencast.paella.versionButton.md'
   - Playlists: configuration/playlists.md
   - Plugin Management: configuration/plugin-management.md
   - Role Based Event Access: 'configuration/episode-id-roles.md'
   - Search Index:
        - Overview: 'configuration/searchindex/index.md'
        - Elasticsearch: 'configuration/searchindex/elasticsearch.md'
   - Serving Static Files: 'configuration/serving-static-files.md'
   - Stream Security:
        - Overview: 'configuration/stream-security/stream-security-overview.md'
        - Configuration: 'configuration/stream-security/stream-security-config.md'
   - Studio: 'configuration/studio.md'
   - Subtitles: 'configuration/subtitles.md'
   - Termination State:
        - Basic: 'configuration/terminationstate.md'
        - AWS AutoScaling: 'configuration/terminationstate.aws.autoscaling.md'
   - Text Extraction: 'configuration/textextraction.md'
   - Timeline Previews: 'configuration/timelinepreviews.md'
   - Transcription configuration:
        - AmberScript: 'configuration/transcription.configuration/amberscripttranscripts.md'
        - Google Speech: 'configuration/transcription.configuration/googlespeechtranscripts.md'
        - IBM Watson: 'configuration/transcription.configuration/watsontranscripts.md'
        - Microsoft Azure: 'configuration/transcription.configuration/microsoftazuretranscripts.md'
        - Vosk: 'configuration/transcription.configuration/vosk.md'
        - Whisper: 'configuration/transcription.configuration/whisper.md'
        - WhisperC++: 'configuration/transcription.configuration/whispercpp.md'
   - User Statistics and Privacy Configuration: 'configuration/user-statistics.and.privacy.md'
   - Video Editor:
        - Overview: 'configuration/videoeditor.overview.md'
        - Architecture: 'configuration/videoeditor.architecture.md'
        - Frontend: 'configuration/videoeditor.frontend.md'
        - Workflow Operations: 'configuration/videoeditor.workflow-operation.md'
   - Video Segmentation: 'configuration/videosegmentation.md'
   - Workflow: 'configuration/workflow.md'
   - Wowza Streaming Distribution Service: 'configuration/streaming-wowza.md'
   - YouTube Publication: 'configuration/youtubepublication.md'
- Version Support: 'version-support.md'
- Workflow Operation Handler:
   - Overview: 'workflowoperationhandlers/index.md'
   - Retry Strategies: 'workflowoperationhandlers/retry-strategies.md'
   - Add Catalog: 'workflowoperationhandlers/add-catalog-woh.md'
   - Analyze Tracks: 'workflowoperationhandlers/analyze-tracks-woh.md'
   - Analyze Mediapackage: 'workflowoperationhandlers/analyze-mediapackage-woh.md'
   - Analyze Audio: 'workflowoperationhandlers/analyzeaudio-woh.md'
   - Animate: 'workflowoperationhandlers/animate-woh.md'
   - AmberScript Start Transcription: 'workflowoperationhandlers/amberscript-start-transcription-woh.md'
   - AmberScript Attach Transcription: 'workflowoperationhandlers/amberscript-attach-transcription-woh.md'
   - Assert: 'workflowoperationhandlers/assert-woh.md'
   - Asset Snapshot: 'workflowoperationhandlers/snapshot-woh.md'
   - Asset Delete: 'workflowoperationhandlers/asset-delete-woh.md'
   - Attach Watson Transcription: 'workflowoperationhandlers/attach-watson-transcription-woh.md'
   - Change Type: 'workflowoperationhandlers/changetype-woh.md'
   - Cleanup: 'workflowoperationhandlers/cleanup-woh.md'
   - Comment: 'workflowoperationhandlers/comment-woh.md'
   - Composite: 'workflowoperationhandlers/composite-woh.md'
   - Concat: 'workflowoperationhandlers/concat-woh.md'
   - Conditional Config: 'workflowoperationhandlers/conditional-config-woh.md'
   - Configure-By-DCTerm: 'workflowoperationhandlers/configure-by-dcterm-woh.md'
   - Copy: 'workflowoperationhandlers/copy-woh.md'
   - Clone: 'workflowoperationhandlers/clone-woh.md'
   - Cover Image: 'workflowoperationhandlers/coverimage-woh.md'
   - Crop Video: 'workflowoperationhandlers/cropvideo-woh.md'
   - Cut Marks To Smil: 'workflowoperationhandlers/cut-marks-to-smil-woh.md'
   - Defaults: 'workflowoperationhandlers/defaults-woh.md'
   - Demux: 'workflowoperationhandlers/demux-woh.md'
   - Duplicate Event: 'workflowoperationhandlers/duplicate-event-woh.md'
   - Editor: 'workflowoperationhandlers/editor-woh.md'
   - Encode: 'workflowoperationhandlers/encode-woh.md'
   - Error Resolution: 'workflowoperationhandlers/error-resolution-woh.md'
   - Execute Once: 'workflowoperationhandlers/execute-once-woh.md'
   - Execute Many: 'workflowoperationhandlers/execute-many-woh.md'
   - Export Workflow Properties: 'workflowoperationhandlers/export-wf-properties-woh.md'
   - Extract Text: 'workflowoperationhandlers/extracttext-woh.md'
   - Google Speech Attach Transcription: 'workflowoperationhandlers/google-speech-attach-transcription-woh.md'
   - Google Speech Start Transcription: 'workflowoperationhandlers/google-speech-start-transcription-woh.md'
   - HTTP Notify: 'workflowoperationhandlers/httpnotify-woh.md'
   - Image: 'workflowoperationhandlers/image-woh.md'
   - Image convert: 'workflowoperationhandlers/image-convert-woh.md'
   - Image to Video: 'workflowoperationhandlers/imagetovideo-woh.md'
   - Import Workflow Properties: 'workflowoperationhandlers/import-wf-properties-woh.md'
   - Incident: 'workflowoperationhandlers/incident-woh.md'
   - Include: 'workflowoperationhandlers/include-woh.md'
   - Ingest-Download: 'workflowoperationhandlers/ingestdownload-woh.md'
   - Inspect: 'workflowoperationhandlers/inspect-woh.md'
   - Log: 'workflowoperationhandlers/log-woh.md'
   - Mattermost Notification Module: 'workflowoperationhandlers/mattermost-notify-woh.md'
   - Metadata to ACL: 'workflowoperationhandlers/metadata-to-acl.md'
   - Move Storage: 'workflowoperationhandlers/move-storage-woh.md'
   - Microsoft Azure Attach Transcription: 'workflowoperationhandlers/microsoft-azure-attach-transcription-woh.md'
   - Microsoft Azure Start Transcription: 'workflowoperationhandlers/microsoft-azure-start-transcription-woh.md'
   - Multiencode: 'workflowoperationhandlers/multiencode-woh.md'
   - Normalize Audio: 'workflowoperationhandlers/normalizeaudio-woh.md'
   - Partial Import: 'workflowoperationhandlers/partial-import-woh.md'
   - Post Media Package: 'workflowoperationhandlers/postmediapackage-woh.md'
   - Prepare A/V: 'workflowoperationhandlers/prepareav-woh.md'
   - Probe Resolution: 'workflowoperationhandlers/probe-resolution-woh.md'
   - Process Smil: 'workflowoperationhandlers/process-smil-woh.md'
   - Publication to Workspace: 'workflowoperationhandlers/publication-to-workspace-woh.md'
   - Publish Configure AWS: 'workflowoperationhandlers/publish-configure-aws-woh.md'
   - Publish Configure: 'workflowoperationhandlers/publish-configure-woh.md'
   - Publish Engage AWS: 'workflowoperationhandlers/publish-engage-aws-woh.md'
   - Publish Engage: 'workflowoperationhandlers/publish-engage-woh.md'
   - Publish OAI-PMH: 'workflowoperationhandlers/publish-oaipmh-woh.md'
   - Publish YouTube: 'workflowoperationhandlers/publish-youtube-woh.md'
   - Rename Files: 'workflowoperationhandlers/rename-files-woh.md'
   - Republish OAI-PMH: 'workflowoperationhandlers/republish-oaipmh-woh.md'
   - Retract Engage AWS: 'workflowoperationhandlers/retract-engage-aws-woh.md'
   - Retract Engage: 'workflowoperationhandlers/retract-engage-woh.md'
   - Retract Configure AWS: 'workflowoperationhandlers/retract-configure-aws-woh.md'
   - Retract Configure: 'workflowoperationhandlers/retract-configure-woh.md'
   - Retract OAI-PMH: 'workflowoperationhandlers/retract-oaipmh-woh.md'
   - Retract Partial AWS: 'workflowoperationhandlers/retract-partial-aws-woh.md'
   - Retract Partial: 'workflowoperationhandlers/retract-partial-woh.md'
   - Retract YouTube: 'workflowoperationhandlers/retract-youtube-woh.md'
   - Sanitize Adaptive: 'workflowoperationhandlers/sanitize-adaptive-woh.md'
   - Segment Previews: 'workflowoperationhandlers/segmentpreviews-woh.md'
   - Segment Video: 'workflowoperationhandlers/segmentvideo-woh.md'
   - Select Tracks: 'workflowoperationhandlers/select-streams-woh.md'
   - Select Version: 'workflowoperationhandlers/select-version-woh.md'
   - Send Email: 'workflowoperationhandlers/send-email-woh.md'
   - Series: 'workflowoperationhandlers/series-woh.md'
   - Silence: 'workflowoperationhandlers/silence-woh.md'
   - Speech to Text: 'workflowoperationhandlers/speechtotext-woh.md'
   - Speech to Text Attach: 'workflowoperationhandlers/speechtotext-attach-woh.md'
   - Start Watson Transcription: 'workflowoperationhandlers/start-watson-transcription-woh.md'
   - Start Workflow: 'workflowoperationhandlers/start-workflow-woh.md'
   - Statistics Writer: 'workflowoperationhandlers/statistics-writer.md'
   - Subtitle Timeshift: 'workflowoperationhandlers/subtitle-timeshift-woh.md'
   - Tag: 'workflowoperationhandlers/tag-woh.md'
   - Tag-By-DCTerm: 'workflowoperationhandlers/tag-by-dcterm-woh.md'
   - Tag-Engage: 'workflowoperationhandlers/tag-engage-woh.md'
   - Timelinepreviews: 'workflowoperationhandlers/timelinepreviews-woh.md'
   - Transfer Metadata: 'workflowoperationhandlers/transfer-metadata-woh.md'
   - Theme: 'workflowoperationhandlers/theme-woh.md'
   - Video Grid: 'workflowoperationhandlers/video-grid-woh.md'
   - Waveform: 'workflowoperationhandlers/waveform-woh.md'
   - WebVTT to CutMarks Operation: 'workflowoperationhandlers/webvtt-to-cutmarks.md'
   - Zip: 'workflowoperationhandlers/zip-woh.md'
