site_name: Administration Guide
repo_url: https://github.com/opencast/opencast
edit_uri: edit/develop/docs/guides/admin/docs/

markdown_extensions:
  - markdown_inline_graphviz

# Default theme used is windmill
theme: windmill

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# The css files in this list will override existing css from the default theme
extra_css:
   - css/extra.css

# The javascript files in this list will extend the existing javascript from the default theme
extra_javascript:
   - javascript/extra.js

# The logo in the header
extra:
   logo: 'opencast-white.svg'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order
nav:
- Home: 'index.md'
- Release Notes: 'releasenotes.md'
- Upgrade: 'upgrade.md'
- Changelog: 'changelog.md'
- Installation:
   - Overview: 'installation/index.md'
   - Multiple Servers: 'installation/multiple-servers.md'
   - Installation from Source:
      - Linux: 'installation/source-linux.md'
      - MacOS X: 'installation/source-macosx.md'
   - Installation from Package:
      - Debian/Ubuntu: 'installation/debs.md'
      - Fedora: 'installation/rpm-fedora.md'
      - RHEL/CentOS 7: 'installation/rpm-el7.md'
      - RHEL/CentOS 8: 'installation/rpm-el8.md'
   - Installation via script:
      - Ansible: 'installation/ansible.md'
   - Installation with Docker:
      - Testing Locally: 'installation/docker-local.md'
- Configuration:
   - Overview: 'configuration/index.md'
   - Basic: 'configuration/basic.md'
   - Database: 'configuration/database.md'
   - HTTPS:
      - Overview: 'configuration/https/index.md'
      - Using Nginx: 'configuration/https/nginx.md'
      - Using Apache httpd: configuration/https/apache-httpd.md
      - Internal HTTPS: 'configuration/https/opencast.only.md'
      - Migrating old content to HTTPS: 'configuration/https/migration.md'
   - Asset Manager: 'configuration/asset-manager.md'
   - Message Broker: 'configuration/message-broker.md'
   - Metadata: 'configuration/metadata.md'
   - Encoding: 'configuration/encoding.md'
   - Inbox: 'configuration/inbox.md'
   - List Providers: 'configuration/listproviders.md'
   - Load: 'configuration/load.md'
   - Log: 'configuration/log.md'
   - User Statistics and Privacy Configuration: 'configuration/user-statistics.and.privacy.md'
   - Multi Tenancy: 'configuration/multi.tenancy.md'
   - Authentication, Autorization and User Management:
      - General Security: 'configuration/security.md'
      - Access Control Lists: 'configuration/acl.md'
      - Authentication and Authorization Infrastructure (AAI): 'configuration/security.aai.md'
      - Central Authentication Service (CAS): 'configuration/security.cas.md'
      - LDAP Authentication and Authorization (without CAS): 'configuration/security.ldap.md'
      - Moodle User Provider: 'configuration/security.user.moodle.md'
      - Sakai User Provider: 'configuration/security.user.sakai.md'
      - Brightspace User Provider: 'configuration/security.user.brightspace.md'
      - Canvas User Provider: 'configuration/security.user.canvas.md'
   - Stream Security: 'configuration/stream-security.md'
   - Workflow: 'configuration/workflow.md'
   - External API: 'configuration/external-api.md'
   - OAI-PMH: 'configuration/oaipmh.md'
   - External Monitoring: 'configuration/monitoring.md'
   - Trim Segments: 'configuration/trim-segments.md'
   - Admin UI Configuration:
      - Event Filters: 'configuration/admin-ui/event-filters.md'
      - Manual Asset Upload: 'configuration/admin-ui/asset-upload.md'
      - Languages: 'configuration/admin-ui/languages.md'
      - Statistics: 'configuration/admin-ui/statistics.md'
      - Thumbnails: 'configuration/admin-ui/thumbnails.md'
      - Role-based Visibility: 'configuration/admin-ui/role-based-visibility.md'
      - Capture-Agent Access: configuration/admin-ui/capture-agent-access.md
- Version Support: 'version-support.md'
- Modules:
   - Overview: 'modules/index.md'
   - Atom/RSS Feed: 'modules/atomrss.md'
   - Amazon Services:
      - Amazon S3 Archive Storage: 'modules/awss3archive.md'
      - Amazon S3 Distribution: 'modules/awss3distribution.md'
   - Execute Service: 'modules/execute.md'
   - Live Schedule: 'modules/liveschedule.md'
   - LTI Module: 'modules/ltimodule.md'
   - Media Module: 'modules/mediamodule.configuration.md'
   - Player:
      - Configuration: 'modules/player.configuration.md'
      - URL Parameters: 'modules/player.url.parameter.md'
      - Matomo Tracking: 'modules/player.matomo.tracking.md'
   - Paella player:
      - Configuration: 'modules/paella.player/configuration.md'
      - URL Parameters: 'modules/paella.player/url.parameter.md'
      - Paella plugins:
        - Overview: 'modules/paella.player/plugins.md'
        - es.upv.paella.opencast.descriptionPlugin: 'modules/paella.player/plugins/es.upv.paella.opencast.descriptionPlugin.md'
        - es.upv.paella.opencast.downloadsPlugin: 'modules/paella.player/plugins/es.upv.paella.opencast.downloadsPlugin.md'
        - es.upv.paella.opencast.episodesFromSeries: 'modules/paella.player/plugins/es.upv.paella.opencast.episodesFromSeries.md'
        - es.upv.paella.opencast.loader: 'modules/paella.player/plugins/es.upv.paella.opencast.loader.md'
        - es.upv.paella.opencast.logIn: 'modules/paella.player/plugins/es.upv.paella.opencast.logIn.md'
        - es.upv.paella.opencast.searchPlugin: 'modules/paella.player/plugins/es.upv.paella.opencast.searchPlugin.md'
        - es.upv.paella.opencast.transcriptionTabBarPlugin: 'modules/paella.player/plugins/es.upv.paella.opencast.transcriptionTabBarPlugin.md'
        - es.upv.paella.opencast.userTrackingSaverPlugIn: 'modules/paella.player/plugins/es.upv.paella.opencast.userTrackingSaverPlugIn.md'
   - Search Index:
      - Overview: 'modules/searchindex/index.md'
      - Solr: 'modules/searchindex/solr.md'
      - Elasticsearch: 'configuration/elasticsearch.md'
   - Stream Security: 'modules/stream-security.md'
   - Studio: 'modules/studio.md'
   - Termination State:
      - Basic: 'modules/terminationstate.md'
      - AWS AutoScaling: 'modules/terminationstate.aws.autoscaling.md'
   - Text Extraction: 'modules/textextraction.md'
   - Timeline Previews: 'modules/timelinepreviews.md'
   - Transcripts (AmberScript): 'modules/amberscripttranscripts.md'
   - Transcripts (Google Speech): 'modules/googlespeechtranscripts.md'
   - Transcripts (IBM Watson): 'modules/watsontranscripts.md'
   - Video Editor:
      - Setup: 'modules/videoeditor.setup.md'
      - Architecture: 'modules/videoeditor.architecture.md'
   - Video Segmentation: 'modules/videosegmentation.md'
   - Waveform Service: 'modules/waveform.md'
   - Wowza Streaming Distribution Service: 'modules/streaming-wowza.md'
   - YouTube Publication: 'modules/youtubepublication.md'
- Workflow Operation Handler:
   - Overview: 'workflowoperationhandlers/index.md'
   - Retry Strategies: 'workflowoperationhandlers/retry-strategies.md'
   - Add Catalog: 'workflowoperationhandlers/add-catalog-woh.md'
   - Analyze Tracks: 'workflowoperationhandlers/analyze-tracks-woh.md'
   - Analyze Audio: 'workflowoperationhandlers/analyzeaudio-woh.md'
   - Animate: 'workflowoperationhandlers/animate-woh.md'
   - AmberScript Start Transcription: 'workflowoperationhandlers/amberscript-start-transcription-woh.md'
   - AmberScript Attach Transcription: 'workflowoperationhandlers/amberscript-attach-transcription-woh.md'
   - Asset Snapshot: 'workflowoperationhandlers/snapshot-woh.md'
   - Asset Delete: 'workflowoperationhandlers/asset-delete-woh.md'
   - Attach Watson Transcription: 'workflowoperationhandlers/attach-watson-transcription-woh.md'
   - Cleanup: 'workflowoperationhandlers/cleanup-woh.md'
   - Comment: 'workflowoperationhandlers/comment-woh.md'
   - Composite: 'workflowoperationhandlers/composite-woh.md'
   - Concat: 'workflowoperationhandlers/concat-woh.md'
   - Configure-By-DCTerm: 'workflowoperationhandlers/configure-by-dcterm-woh.md'
   - Copy: 'workflowoperationhandlers/copy-woh.md'
   - Clone: 'workflowoperationhandlers/clone-woh.md'
   - Cover Image: 'workflowoperationhandlers/coverimage-woh.md'
   - Crop Video: 'workflowoperationhandlers/cropvideo-woh.md'
   - Defaults: 'workflowoperationhandlers/defaults-woh.md'
   - Demux: 'workflowoperationhandlers/demux-woh.md'
   - Duplicate Event: 'workflowoperationhandlers/duplicate-event-woh.md'
   - Editor: 'workflowoperationhandlers/editor-woh.md'
   - Encode: 'workflowoperationhandlers/encode-woh.md'
   - Error Resolution: 'workflowoperationhandlers/error-resolution-woh.md'
   - Execute Once: 'workflowoperationhandlers/execute-once-woh.md'
   - Execute Many: 'workflowoperationhandlers/execute-many-woh.md'
   - Export Workflow Properties: 'workflowoperationhandlers/export-wf-properties-woh.md'
   - Extract Text: 'workflowoperationhandlers/extracttext-woh.md'
   - Failing: 'workflowoperationhandlers/failing-woh.md'
   - Google Speech Attach Transcription: 'workflowoperationhandlers/google-speech-attach-transcription-woh.md'
   - Google Speech Start Transcription: 'workflowoperationhandlers/google-speech-start-transcription-woh.md'
   - HTTP Notify: 'workflowoperationhandlers/httpnotify-woh.md'
   - Image: 'workflowoperationhandlers/image-woh.md'
   - Image convert: 'workflowoperationhandlers/image-convert-woh.md'
   - Image to Video: 'workflowoperationhandlers/imagetovideo-woh.md'
   - Import Workflow Properties: 'workflowoperationhandlers/import-wf-properties-woh.md'
   - Incident: 'workflowoperationhandlers/incident-woh.md'
   - Include: 'workflowoperationhandlers/include-woh.md'
   - Ingest-Download: 'workflowoperationhandlers/ingestdownload-woh.md'
   - Inspect: 'workflowoperationhandlers/inspect-woh.md'
   - Log: 'workflowoperationhandlers/log-woh.md'
   - Mattermost Notification Module: 'workflowoperationhandlers/notification.md'
   - Move Storage: 'workflowoperationhandlers/move-storage-woh.md'
   - Multiencode: 'workflowoperationhandlers/multiencode-woh.md'
   - Normalize Audio: 'workflowoperationhandlers/normalizeaudio-woh.md'
   - Partial Import: 'workflowoperationhandlers/partial-import-woh.md'
   - Post Media Package: 'workflowoperationhandlers/postmediapackage-woh.md'
   - Prepare A/V: 'workflowoperationhandlers/prepareav-woh.md'
   - Probe Resolution: 'workflowoperationhandlers/probe-resolution-woh.md'
   - Process Smil: 'workflowoperationhandlers/process-smil-woh.md'
   - Publish AWS: 'workflowoperationhandlers/publish-aws-woh.md'
   - Publish Configure: 'workflowoperationhandlers/publish-configure-woh.md'
   - Publish Engage: 'workflowoperationhandlers/publish-engage-woh.md'
   - Publish OAI-PMH: 'workflowoperationhandlers/publish-oaipmh-woh.md'
   - Publish YouTube: 'workflowoperationhandlers/publish-youtube-woh.md'
   - Republish OAI-PMH: 'workflowoperationhandlers/republish-oaipmh-woh.md'
   - Retract AWS S3 and Cloudfront: 'workflowoperationhandlers/retract-aws-woh.md'
   - Retract Engage: 'workflowoperationhandlers/retract-engage-woh.md'
   - Retract Configure: 'workflowoperationhandlers/retract-configure-woh.md'
   - Retract OAI-PMH: 'workflowoperationhandlers/retract-oaipmh-woh.md'
   - Retract Partial: 'workflowoperationhandlers/retract-partial-woh.md'
   - Retract YouTube: 'workflowoperationhandlers/retract-youtube-woh.md'
   - Sanitize Adaptive: 'workflowoperationhandlers/sanitize-adaptive-woh.md'
   - Segment Previews: 'workflowoperationhandlers/segmentpreviews-woh.md'
   - Segment Video: 'workflowoperationhandlers/segmentvideo-woh.md'
   - Select Streams: 'workflowoperationhandlers/select-streams-woh.md'
   - Send Email: 'workflowoperationhandlers/send-email-woh.md'
   - Series: 'workflowoperationhandlers/series-woh.md'
   - Silence: 'workflowoperationhandlers/silence-woh.md'
   - Start Watson Transcription: 'workflowoperationhandlers/start-watson-transcription-woh.md'
   - Start Workflow: 'workflowoperationhandlers/start-workflow-woh.md'
   - Statistics Writer: 'workflowoperationhandlers/statistics-writer.md'
   - Tag: 'workflowoperationhandlers/tag-woh.md'
   - Tag-By-DCTerm: 'workflowoperationhandlers/tag-by-dcterm-woh.md'
   - Timelinepreviews: 'workflowoperationhandlers/timelinepreviews-woh.md'
   - Transfer Metadata: 'workflowoperationhandlers/transfer-metadata-woh.md'
   - Theme: 'workflowoperationhandlers/theme-woh.md'
   - Video Grid: 'workflowoperationhandlers/video-grid-woh.md'
   - Waveform: 'workflowoperationhandlers/waveform-woh.md'
   - Zip: 'workflowoperationhandlers/zip-woh.md'
