

site_name: Opencast - Developer Guide
repo_url: https://bitbucket.org/opencast-community/matterhorn/src/develop/docs/guides/developer/docs

# Default theme used is readthedocs
theme: readthedocs

# Some of the themes elements can be overridded by elements in this folder
# Note: this is currently not working in on ReadTheDocs
theme_dir: 'theme_override'

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order

pages:
- ['index.md', 'Home']
- ['proposal-log.md', 'Proposal Log']
- ['packaging.md', 'Packaging']
