site_name: Developer Guide
repo_url: https://github.com/opencast/opencast
edit_uri: edit/develop/docs/guides/developer/docs/

plugins:
  - search:
  - mermaid2:
      arguments:
        theme: 'neutral'

# Default theme used is windmill
theme: 'windmill'

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# The css files in this list will override existing css from the default theme
extra_css:
  - css/extra.css

# The javascript files in this list will extend the existing javascript from the default theme
extra_javascript:
  - javascript/extra.js

# The logo in the header
extra:
  logo: 'img/opencast-white.svg'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order
nav:
- Home: 'index.md'
- Participate:
   - Development process: 'participate/development-process.md'
   - Committers: 'participate/committer.md'
   - Release manager: 'participate/release-manager.md'
   - QA coordinator: 'participate/qa-coordinator.md'
   - Localization: 'participate/localization.md'
   - Submit issues:
      - Overview and How to: 'participate/submit-issues/submit-issues.md'
      - Security issues: participate/submit-issues/security.md
   - Decision making:
      - Overview: 'participate/decision-making/index.md'
      - Lazy consensus: 'participate/decision-making/lazy-consensus.md'
      - Consensus building: 'participate/decision-making/consensus-building.md'
      - Voting: 'participate/decision-making/voting.md'
   - Governance: 'participate/governance.md'
   - Services infrastructure:
      - Overview: 'participate/infrastructure/index.md'
      - Maven repository: 'participate/infrastructure/maven-repository.md'
      - Packaging: 'participate/infrastructure/packaging.md'
   - Proposal log: 'participate/proposal-log.md'
- Develop:
   - Setup dev environment:
      - General: 'develop/setup-opencast-for-develop.md'
      - With Docker: 'develop/development-environment-docker.md'
   - Tips for developing: 'develop/development-tips.md'
   - Dev ops:
      - Local cluster for testing: 'develop/devops/local-cluster.md'
      - Explore H2 database: 'develop/devops/explore-h2-database.md'
   - Code style: 'develop/code-style.md'
   - Debugging: 'develop/debugging.md'
   - Frontend development:
      - Overview: 'develop/admin-ui/development.md'
      - Style:
         - Alerts indicators: 'develop/admin-ui/style/alerts-indicators.md'
         - Buttons: 'develop/admin-ui/style/buttons.md'
         - Color-palette: 'develop/admin-ui/style/color-palette.md'
         - dropdowns: 'develop/admin-ui/style/dropdowns.md'
         - Forms: 'develop/admin-ui/style/forms.md'
         - Icons: 'develop/admin-ui/style/icons.md'
         - Index: 'develop/admin-ui/style/index.md'
         - Modals: 'develop/admin-ui/style/modals.md'
         - Navigation: 'develop/admin-ui/style/navigation.md'
         - References: 'develop/admin-ui/style/references.md'
         - Spacing: 'develop/admin-ui/style/spacing.md'
         - Typeface: 'develop/admin-ui/style/typeface.md'
         - View Structure: 'develop/admin-ui/style/view-structure.md'
   - Documentation: 'develop/documentation.md'
- Opencast architecture:
   - Overview: 'architecture/overview.md'
   - Admin-UI: 'architecture/admin-ui.md'
   - Asset manager: 'architecture/asset-manager.md'
   - Capture agent:
      - Introduction: 'architecture/capture-agent/capture-agent.md'
      - Input: 'architecture/capture-agent/capture-agent-input.md'
      - Test Cases for Capture Agents: 'architecture/capture-agent/testcases.md'
   - External API:
      - Introduction: 'architecture/api/index.md'
      - Usage: 'architecture/api/usage.md'
      - Authentication: 'architecture/api/authentication.md'
      - Authorization: 'architecture/api/authorization.md'
      - Base API: 'architecture/api/base-api.md'
      - Agents API: 'architecture/api/agents-api.md'
      - Events API: 'architecture/api/events-api.md'
      - ListProvider API: 'architecture/api/listprovider-api.md'
      - Series API: 'architecture/api/series-api.md'
      - Statistics API: 'architecture/api/statistics-api.md'
      - Groups API: 'architecture/api/groups-api.md'
      - Security API: 'architecture/api/security-api.md'
      - Workflow API: 'architecture/api/workflow-api.md'
      - Data Types: 'architecture/api/types.md'
      - Glossary: 'architecture/api/glossary.md'
   - Filesystem: 'architecture/filesystem.md'
   - Job dispatch: 'architecture/job-dispatch.md'
   - OAI-PMH: 'architecture/oaipmh.md'
   - Paella player 7: 'architecture/paella-player-7/index.md'
   - Scheduler: 'architecture/scheduler.md'
   - Statistics: 'architecture/statistics.md'
   - Stream security: 'architecture/stream-security.md'
- Licenses and Legal Matters: 'license.md'
- Glossary: 'glossary.md'

