site_name: Opencast - Developer Guide
repo_url: https://github.com/opencast/opencast/tree/develop/docs/guides/developer/docs

# Default theme used is readthedocs
theme: readthedocs

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

extra_css:
    - css/font-awesome.min.css
    - css/style-guide.css

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order
pages:
- Home: 'index.md'
- Development Process:
   - Development: 'development-process.md'
   - Reviewing, Merging and Declining Pull Requests: 'reviewing-and-merging.md'
   - Release Manager: 'release-manager.md'
   - QA Coordinator: 'qa-coordinator.md'
   - Security Issues: 'security.md'
   - Code Style: 'code-style.md'
   - Documentation: 'documentation.md'
- Decision Making:
   - Overview: 'decision-making/index.md'
   - Lazy Consensus: 'decision-making/lazy-consensus.md'
   - Consensus Building: 'decision-making/consensus-building.md'
   - Voting: 'decision-making/voting.md'
- Development Environment:
   - Overview: 'development-environment.md'
   - With Docker: 'development-environment-docker.md'
- Committers: 'committer.md'
- Licenses and Legal Matters: 'license.md'
- Governance: 'governance.md'
- Localization: 'localization.md'
- Packaging: 'packaging.md'
- Proposal Log: 'proposal-log.md'
- Asset Manager: 'asset-manager.md'
- Scheduler: 'scheduler.md'
- Modules:
   - Overview: 'modules/index.md'
   - Administrative user Interface:
      - Development: 'modules/admin-ui/development.md'
      - Style Guide:
        - Overview: 'modules/admin-ui/style/index.md'
        - Color Palette: 'modules/admin-ui/style/color-palette.md'
        - Typeface: 'modules/admin-ui/style/typeface.md'
        - View Structure: 'modules/admin-ui/style/view-structure.md'
        - Logo: 'modules/admin-ui/style/spacing.md'
        - Navigation: 'modules/admin-ui/style/navigation.md'
        - Modals: 'modules/admin-ui/style/modals.md'
        - Forms: 'modules/admin-ui/style/forms.md'
        - Icons: 'modules/admin-ui/style/icons.md'
        - Buttons: 'modules/admin-ui/style/buttons.md'
        - Dropdowns: 'modules/admin-ui/style/dropdowns.md'
        - Alerts and Indicators: 'modules/admin-ui/style/alerts-indicators.md'
        - References: 'modules/admin-ui/style/references.md'
   - Capture Agent: 'modules/capture-agent.md'
   - Player:
      - Architecture: 'modules/player/architecture.md'
      - Core Reference: 'modules/player/core.reference.md'
      - Events: 'modules/player/events.md'
      - Storage: 'modules/player/storage.md'
      - Plugin Development: 'modules/player/plugin.development.md'
      - Testing: 'modules/player/testing.md'
   - Stream Security: 'modules/stream-security.md'
   - OAI-PMH: 'modules/oaipmh.md'
- Infrastructure:
   - Overview: 'infrastructure/index.md'
   - Notes: 'infrastructure/notes.md'
   - Maven Repository: 'infrastructure/maven-repository.md'
- External API:
   - Introduction: 'api/index.md'
   - Usage: 'api/usage.md'
   - Authentication: 'api/authentication.md'
   - Authorization: 'api/authorization.md'
   - Base API: 'api/base-api.md'
   - Agents API: 'api/agents-api.md'
   - Events API: 'api/events-api.md'
   - Series API: 'api/series-api.md'
   - Groups API: 'api/groups-api.md'
   - Security API: 'api/security-api.md'
   - Workflow API: 'api/workflow-api.md'
   - Data Types: 'api/types.md'
   - Glossary: 'api/glossary.md'
