version: '2'
services:
  elasticsearch:
    container_name: opencast-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Dlog4j2.formatMsgNoLookups=true'
  postgresql:
    container_name: opencast-postgresql
    image: docker.io/library/postgres:13.2
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: opencast
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: opencast
  mariadb:
    container_name: opencast-mariadb
    image: docker.io/library/mariadb:10.5.9
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: opencast
      MYSQL_DATABASE: opencast
      MYSQL_USER: opencast
      MYSQL_PASSWORD: dbpassword
