version: '2'
services:
  elasticsearch:
    container_name: opencast-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Dlog4j2.formatMsgNoLookups=true'
