on:
  push:
    workflow_dispatch:
    tags:
      - '*.*'

name: Create new release
jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: install dependencies
        run: |
          sudo apt update -q
          sudo apt install -y -q \
            bzip2 \
            gzip \
            tar \
            unzip

      - name: build opencast
        run: |
          mvn clean install \
            --batch-mode \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Dhttp.keepAlive=false \
            -Dmaven.wagon.http.pool=false \
            -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
            -DskipTests \
            -Dcheckstyle.skip=true

      - name: Get the version
        id: get_version
        run: |
          echo "::set-output name=VERSION::$GITHUB_REF" | sed 's_refs/tags/\([0-9]*\).\([0-9]*\)$_\1.\2_'
          echo "::set-output name=VERSION_MAIN::$GITHUB_REF" | sed 's_refs/tags/\([0-9]*\).\([0-9]*\)$_\1_'
          echo "::set-output name=VERSION_COMBINED::$GITHUB_REF" | sed 's_refs/tags/\([0-9]*\).\([0-9]*\)$_\1\2_'

      - name: create new release
        uses: softprops/action-gh-release@v2
        with:
          files: build/opencast-dist-*.tar.gz
          fail_on_unmatched_files: true
          name: Opencast ${{ steps.get_version.outputs.VERSION }}
          body: |
            This is an Opencast ${{ steps.get_version.outputs.VERSION_MAIN }} release.
            For further information, please take a look at:

            - [Release notes](https://docs.opencast.org/r/${{ steps.get_version.outputs.VERSION_MAIN }}.x/admin/#releasenotes/#opencast-${{ steps.get_version.outputs.VERSION_COMBINED }})
            - [Changelog](https://docs.opencast.org/r/${{ steps.get_version.outputs.VERSION_MAIN }}.x/admin/#changelog/#opencast-${{ steps.get_version.outputs.VERSION_COMBINED }})
