name: Deploy Tobira Opencast

on:
  workflow_dispatch:

concurrency:
  group: global
  cancel-in-progress: false

jobs:
  build:
    name: deploy tobira opencast
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt update -q
          sudo apt install -y -q bzip2 gzip tar unzip

      - name: install ansible
        run: pip3 install ansible dnspython

      - name: prepare ssh
        env:
          DEPLOY_KEY: ${{ secrets.TOBIRA_DEPLOY_KEY }}
          SSH_CONFIG: ${{ secrets.TOBIRA_SSH_CONFIG }}
        run: |
          install -dm 700 ~/.ssh/
          echo "${DEPLOY_KEY}" > ~/.ssh/id_ed25519
          echo "${SSH_CONFIG}" > ~/.ssh/config
          chmod 600 ~/.ssh/*

      - name: install ansible roles
        working-directory: .deployment
        run: ansible-galaxy install -r requirements.yml

      - name: deploy
        env:
          OPENCAST_ADMIN_PASSWORD: ${{ secrets.TOBIRA_OPENCAST_ADMIN_PASSWORD }}
          OPENCAST_DIGEST_PASSWORD: ${{ secrets.TOBIRA_OPENCAST_DIGEST_PASSWORD }}
          OPENCAST_POSTGRESQL_PASSWORD: ${{ secrets.TOBIRA_OPENCAST_POSTGRESQL_PASSWORD }}
          OPENCAST_LETSENCRYPT_EMAIL: ${{ secrets.TOBIRA_OPENCAST_LETSENCRYPT_EMAIL }}
          ANSIBLE_HOST_KEY_CHECKING: false
        working-directory: .deployment
        run: ansible-playbook deploy.yml
